# Generated by Django 4.2.26 on 2025-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0009_columnmetadata_file_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmetadata',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
